version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mycontainer-01
    image: myimage:1.06
    restart: always
    ports: 
    - "8081:8080"

    volumes: 
    - myvol
    networks:
    - mynet

networks:
  mynet:
    driver: bridge
